Вспомогательные программы
htmlacademy-javascript/1763669-kekstagram-24 pull request #2
Opened 2021-09-26 02:22 UTC by tkornilova

2021-09-26 17:56 UTC, alexjavascript requested changes
Необходимо пройти тесты на ESLint

2021-09-27 19:11 UTC, mikhailkaryamin reviewed
В целом все хорошо, но есть несколько недочетов.

- в первой функции мы может передать минимальное и максимальное значение одинаковое `randomIntegerNumber(10, 10)` а в условии указано, что должна быть ошибка (во второй функции тоже потребуется этот знак сравнения)
- во второй функции по условию,
> // Результат: true, если строка проходит по длине, и false — если не проходит
т.е. функция должна вернуть Boolean значение `true` или `false`,

2021-09-27 19:11 UTC, mikhailkaryamin commented on js/main.js
> +let userCommentLength;
это излишняя переменная, в данном случаи у нас функция принимает два аргумента, и этих аргументов ( если по простому, то аргументы становятся переменными внутри функции) будет достаточно для выполнения

2021-09-27 19:11 UTC, mikhailkaryamin commented on js/main.js
> +  if (maxLength > userCommentLength) {
стоит задуматься, а в какой строчке кода у тебя присваивается какое-то значение для `userCommentLength`

2021-09-28 05:02 UTC, merged